# Config file for liver fibrosis staging and segmentation

# General training
exp_name: liver
pretrained_ckpt: "../anatomix-main/model-weights/anatomix.pth"

seed: 12345
n_epochs: 500
val_interval: 1
batch_size: 2
lr: 2e-4
weight_decay: 1e-5
max_ckpt: 3
max_best_ckpt: 5

consistency_weight: 0.01
semisup_dice: 0.85

cls_modal_dropout: 0.5
cls_batch_size: 5
cls_lr: 3e-5
cls_main_loss_weights: [0.163193,   0.24733941, 0.49467883, 0.09478876]
cls_aux1_loss_weights: [0.73055553, 0.26944444]
cls_aux2_loss_weights: [0.46388888, 0.5361111 ]
cls_aux_loss_weights: [1.0, 1.0]

# Dataset
num_modals: 7
n_cls_classes: 4

n_classes: 1
num_workers: 16

data_dir: "../Data/CARE-Liver/LiQA_training_data/"
process_data_dir: "../Data_preprocess/CARE-Liver/LiQA_training_data/"
other_data_dirs: ["../Data_preprocess/CHAOS_MRI/"]

multisets: [True, True]
set_length: [150, 150]

transform_kwargs:
  patch_size: [128, 128, 128]
  spacing: [2.0, 2.0, 2.0]

